### ISSUE TITLE
Ordering of files, README.md position, Windows

### ISSUE THREAD

**Issue by tyllyn** [BarkleyREI/brei-util#2]
brei-assemble-helpers\test\test.js is failing as shown below

![image](https://user-images.githubusercontent.com/159615/68340210-f9e67f00-00b3-11ea-8e14-eb327647851e.png)

README.md is appearing below the lowercase files, but is expected above. I believe this might be related to the children assignment under the tree(filename) function in brei-util\index.js (lines 36-40) and possibly differences in how this is handled under a Windows environment.

**Comment by nessthehero** [comment]
I removed all the object comparison tests from all the sub repos.
